### ISSUE TITLE
账密不正确时没有报错 以及 密码中含有')'时报错

### ISSUE THREAD

**Issue by Miroier** [Robotxm/AutoXduNCovReport#1]
账密错误时依然显示正确的绿勾勾，如果显示红叉或许更好些
![image](https://user-images.githubusercontent.com/45321964/110964996-bf1ee600-838e-11eb-9719-5bcf4264f5c9.png)

在我update了secrets之后 报了下图的错误，我想这应该是因为我的密码中含有‘)’  
![image](https://user-images.githubusercontent.com/45321964/110964462-2daf7400-838e-11eb-9e25-14a56dbcaecc.png)

**Comment by Robotxm** [comment]
关于如何在账号密码错误的情况下让 GitHub Actions 显示红叉，我回头研究一下。
另外就是如果密码里有特殊字符的话需要用双引号引起来，这个我更新一下 YAML。

**Comment by Robotxm** [comment]
已更新，同步最新代码即可。
